<a href="https://colab.research.google.com/github/tanvi20206/heart-prediction-neural--network/blob/main/heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
dataset = pd.read_csv('heart.csv')
x = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, -1].values


In [ ]:
print(x)


[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [ ]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [ ]:



from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)


from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


ann.fit(x_train,y_train,batch_size=32,epochs=80)
print(ann.predict(sc.transform([[50,1,1,172,221,1,0,160,0,1.5,1,3,2]])))

print(ann.predict(sc.transform([[50,1,1,172,221,1,0,160,0,1.5,1,3,2]]))>0.5)

Epoch 1/80
8/8 [==============================] - 1s 2ms/step - loss: 0.7542 - accuracy: 0.4380
Epoch 2/80
8/8 [==============================] - 0s 2ms/step - loss: 0.7388 - accuracy: 0.4628
Epoch 3/80
8/8 [==============================] - 0s 2ms/step - loss: 0.7237 - accuracy: 0.4752
Epoch 4/80
8/8 [==============================] - 0s 2ms/step - loss: 0.7102 - accuracy: 0.5124
Epoch 5/80
8/8 [==============================] - 0s 3ms/step - loss: 0.6975 - accuracy: 0.5537
Epoch 6/80
8/8 [==============================] - 0s 3ms/step - loss: 0.6853 - accuracy: 0.5744
Epoch 7/80
8/8 [==============================] - 0s 2ms/step - loss: 0.6727 - accuracy: 0.5868
Epoch 8/80
8/8 [==============================] - 0s 2ms/step - loss: 0.6609 - accuracy: 0.6074
Epoch 9/80
8/8 [==============================] - 0s 3ms/step - loss: 0.6501 - accuracy: 0.6281
Epoch 10/80
8/8 [==============================] - 0s 2ms/step - loss: 0.6387 - accuracy: 0.6570
Epoch 11/80
8/8 [======================